
CREATE TABLE TBSI_LN
(
  LN_CD            CHAR(3)                 NOT NULL,
  APL_ST_DT        CHAR(8)                 NOT NULL,
  APL_CLS_DT       CHAR(8)                 NOT NULL,
  LN_NM            VARCHAR(20)             NOT NULL,
  SD_LN_DV_CD      CHAR(1)
);

CREATE UNIQUE INDEX PK_TBSI_LN ON TBSI_LN (LN_CD, APL_ST_DT);

CREATE INDEX IDX_TBSI_LN ON TBSI_LN (LN_CD, APL_ST_DT, APL_CLS_DT);

ALTER TABLE TBSI_LN ADD (CONSTRAINT PK_TBSI_LN PRIMARY KEY (LN_CD, APL_ST_DT));
