
CREATE TABLE TBSI_RT_STN
(
  ROUT_CD         CHAR(5)                  NOT NULL,
  APL_ST_DT       CHAR(8)                  NOT NULL,
  STN_ORDR        INT(3)                   NOT NULL,
  STN_CD          CHAR(8)                  NOT NULL,
  LN_ORDR         INT(2)                   NOT NULL,
  LN_CD           CHAR(3)                  NOT NULL,
  ACM_KM          FLOAT(5,1)               NOT NULL
);

CREATE UNIQUE INDEX PK_TBSI_RT_STN ON TBSI_RT_STN (ROUT_CD, APL_ST_DT, STN_ORDR);

ALTER TABLE TBSI_RT_STN ADD (CONSTRAINT PK_TBSI_RT_STN PRIMARY KEY (ROUT_CD, APL_ST_DT, STN_ORDR));

ALTER TABLE TBSI_RT_STN ADD (CONSTRAINT FK_TBSI_RT_STN_01 FOREIGN KEY (ROUT_CD, APL_ST_DT)
                                REFERENCES TBSI_RT (ROUT_CD, APL_ST_DT));

ALTER TABLE TBSI_RT_STN ADD (CONSTRAINT FK_TBSI_RT_STN_02 FOREIGN KEY (ROUT_CD, APL_ST_DT, LN_ORDR)
                                REFERENCES TBSI_RT_LN (ROUT_CD, APL_ST_DT, LN_ORDR));

