
CREATE TABLE TBSI_STN
(
  STN_CD             CHAR(8)               NOT NULL,
  APL_ST_DT          CHAR(8)               NOT NULL,
  APL_CLS_DT         CHAR(8)               NOT NULL,
  STN_KND_CD         CHAR(2)               NOT NULL,
  STN_NM             VARCHAR(12)           NOT NULL,
  CHG_STN_FLG        CHAR(1)
);

CREATE UNIQUE INDEX PK_TBSI_STN ON TBSI_STN (STN_CD, APL_ST_DT);

CREATE INDEX IDX_TBSI_STN ON TBSI_STN (STN_CD, APL_ST_DT, APL_CLS_DT);

ALTER TABLE TBSI_STN ADD (CONSTRAINT PK_TBSI_STN PRIMARY KEY (STN_CD, APL_ST_DT));
