
CREATE TABLE TBSI_RT
(
  ROUT_CD         CHAR(5)                  NOT NULL,
  APL_ST_DT       CHAR(8)                  NOT NULL,
  APL_CLS_DT      CHAR(8)                  NOT NULL,
  ROUT_NM         VARCHAR(40),
  ROUT_ST_STN_CD  CHAR(8)                  NOT NULL,
  ROUT_CLS_STN_CD CHAR(8)                  NOT NULL,
  ROUT_DV_CD      CHAR(2)                  NOT NULL
);

CREATE UNIQUE INDEX PK_TBSI_RT ON TBSI_RT (ROUT_CD, APL_ST_DT);

CREATE INDEX IDX_TBSI_RT ON TBSI_RT (ROUT_CD, APL_ST_DT, APL_CLS_DT);

ALTER TABLE TBSI_RT ADD (CONSTRAINT PK_TBSI_RT PRIMARY KEY (ROUT_CD, APL_ST_DT));
