
CREATE TABLE TBCM_COM_CD
(
  COM_GRP_CD       VARCHAR(20)            NOT NULL,
  COM_CD           VARCHAR(10)            NOT NULL,
  COM_CD_NM        VARCHAR(40)            NOT NULL,
  COM_CD_SQNO      INT(3)                 NOT NULL
);

CREATE UNIQUE INDEX PK_TBCM_COM_CD ON TBCM_COM_CD (COM_GRP_CD, COM_CD, COM_CD_SQNO);

ALTER TABLE TBCM_COM_CD ADD (CONSTRAINT PK_TBCM_COM_CD PRIMARY KEY (COM_GRP_CD, COM_CD, COM_CD_SQNO));
