
CREATE TABLE TBCM_CAL
(
  RUN_DT           CHAR(8)                 NOT NULL,
  APL_DAY_CD       CHAR(1)                 NOT NULL,
  INT_DAY_CD       CHAR(1),
  TMP_DAY_CD       CHAR(1)
);

CREATE UNIQUE INDEX PK_TBCM_CAL ON TBCM_CAL (RUN_DT);

ALTER TABLE TBCM_CAL ADD (CONSTRAINT PK_TBCM_CAL PRIMARY KEY (RUN_DT));
